### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by KimpiegamesYT1** [re-ovo/Matrix-Issues#2357]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  Spigot 1.16.5 
**Verbose messages**:  See Video
**How/when does this happen**: It only happens when you get pushed and interact with something 
**Video of false positive**: https://youtu.be/ccR9uNL9LeE
**Other information**: The push works just good, Only when you interact it happens 

## Configuration Files
**Link to checks.yml file**: Its a default config

**Comment by jiangdashao** [comment]
what

**Comment by KimpiegamesYT1** [comment]
You don't see the false positives? Watch the video.
It happens when I get pushed and interact with a block. 
I also get another ton of false intract errors.
