### ISSUE TITLE
[FP] Phase

### ISSUE THREAD

**Issue by rmalca** [re-ovo/Matrix-Issues#2365]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Papermc 1.16.5
**Verbose messages**:
(13:03:05) LeftReaver failed Phase check | moved into block (block: stone, move: 0.008,0.034,0.226, at: -3.652,4.2,-199.058, dist: 0.226, loop: false) (+2) | vl:2 ping:72 tps:20.0 lp:7 component: phase.main ver: 1.16.x
(13:03:05) LeftReaver failed Phase check | moved into block (block: andesite, move: 0.018,0.2,0.49, at: -3.581,4.2,-197.145, dist: 0.491, loop: false) (+4) | vl:6 ping:72 tps:20.0 lp:7 component: phase.main ver: 1.16.x
(13:03:16) LeftReaver failed Phase check | moved into block (block: stone, move: 0.001,0.034,-0.054, at: -3.562,4.2,-205.811, dist: 0.054, loop: false) (+2) | vl:2 ping:71 tps:20.0 lp:3 component: phase.main ver: 1.16.x
(13:03:47) LeftReaver failed Phase check | moved into block (block: stone, move: 0.004,0.034,0.054, at: -3.55,3.2,-204.189, dist: 0.054, loop: false) (+2) | vl:2 ping:221 tps:20.0 lp:11 component: phase.main ver: 1.16.x
(13:03:48) LeftReaver failed Phase check | moved into block (block: stone, move: 0.018,0.034,0.285, at: -3.558,4.2,-198.517, dist: 0.286, loop: false) (+2) | vl:4 ping:221 tps:20.0 lp:8 component: phase.main ver: 1.16.x
(13:03:50) LeftReaver failed Phase check | moved into block (block: stone, move: 0.019,0.2,-0.48, at: -3.39,3.2,-204.757, dist: 0.481, loop: false) (+4) | vl:8 ping:71 tps:20.0 lp:5 component: phase.main ver: 1.16.x
(13:03:50) Execute command: matrix notify LeftReaver puede que haya pasado a través de un bloque (Phase)
(13:03:51) LeftReaver failed Phase check | moved into block (block: stone, move: -0.034,0.034,-0.053, at: -3.469,4.2,-205.807, dist: 0.063, loop: false) (+2) | vl:10 ping:71 tps:19.99 lp:5 component: phase.main ver: 1.16.x
(13:03:59) LeftReaver failed Phase check | moved into block (block: stone, move: 0.009,0.034,0.06, at: -3.538,4.2,-199.183, dist: 0.06, loop: false) (+2) | vl:12 ping:71 tps:20.0 lp:3 component: phase.main ver: 1.16.x
(13:04:02) LeftReaver failed Phase check | moved into block (block: stone, move: -0.031,0.034,0.059, at: -3.66,4.2,-199.184, dist: 0.067, loop: false) (+2) | vl:14 ping:77 tps:20.0 lp:4 component: phase.main ver: 1.16.x
(13:04:02) Execute command: matrix notify LeftReaver intentó pasar a través de un bloque (Phase)
(13:04:05) LeftReaver failed Phase check | moved into block (block: stone, move: 0.005,0.034,0.283, at: -3.3,4.2,-198.542, dist: 0.283, loop: false) (+2) | vl:16 ping:77 tps:20.0 lp:4 component: phase.main ver: 1.16.x
(13:04:08) LeftReaver failed Phase check | moved into block (block: stone, move: 0.022,0.034,0.064, at: -3.338,4.2,-199.168, dist: 0.068, loop: false) (+2) | vl:18 ping:77 tps:20.0 lp:5 component: phase.main ver: 1.16.x
(13:04:11) LeftReaver failed Phase check | moved into block (block: stone, move: -0.006,0.034,0.272, at: -3.672,4.2,-198.634, dist: 0.272, loop: false) (+2) | vl:5 ping:72 tps:20.0 lp:5 component: phase.main ver: 1.16.x
(13:04:13) LeftReaver failed Phase check | moved into block (block: stone, move: 0.009,0.034,0.059, at: -3.354,4.2,-199.184, dist: 0.06, loop: false) (+2) | vl:7 ping:72 tps:20.0 lp:4 component: phase.main ver: 1.16.x
(13:04:13) Execute command: matrix notify LeftReaver puede que haya pasado a través de un bloque (Phase)

**How/when does this happen**: 
Apparently it happens when the players are at low altitudes. 

**Video of false positive**: 
https://user-images.githubusercontent.com/3759745/116791158-10d61980-aa7e-11eb-8314-41133b5aa7d0.mp4

**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://pastebin.com/2dy8ZjmY

**Comment by DontNeedAName** [comment]
Seems to generally happen when players jump against blocks and ceilings. Especially noticeable with non full blocks like slabs and stairs. Phase check needs a recode or something. It's really unstable.

**Comment by rmalca** [comment]
Yes, it has also happened to me but without being able to reproduce it. In the case that I present, they are all solid blocks but in low altitude.
