### ISSUE TITLE
[INCOMPATIBILITY] CombatLog or CombatLogX

### ISSUE THREAD

**Issue by botta96** [re-ovo/Matrix-Issues#2369]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  paper spigot 1.8.8
**Incompatible plugin**: [Combatlog](https://www.spigotmc.org/resources/combatlogx.31689/)
**Verbose messages (or) console errors**: NONE
**How/when does this happen**: when the user who is in pvp is killed by the combatlog he loses his inventory and is kicked, on his return without any object in hand, the user is able to inflict damage as if he had the previous objects he used before the kick, removing matrix the problem disappears
**Video of incompatibility**: https://youtu.be/tVwR9Nt0jxI
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by jiangdashao** [comment]
Record a video

**Comment by botta96** [comment]
https://youtu.be/tVwR9Nt0jxI

**Comment by jiangdashao** [comment]
which combat log plugin are u using

**Comment by botta96** [comment]
i have tried with different combatlog, it also works with the latest version of combatlogx

**Comment by jiangdashao** [comment]
plugin link?

**Comment by botta96** [comment]
https://www.spigotmc.org/resources/combatlogx.31689/
