### ISSUE TITLE
[FP] Move

### ISSUE THREAD

**Issue by DontNeedAName** [re-ovo/Matrix-Issues#2372]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [x] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 3056-Spigot-4225eac-6f55b5b (MC: 1.16.5)
**Verbose messages**: in video
**How/when does this happen**: When jumping around edges.
**Video of false positive**: https://youtu.be/EcyocRzc-aU
**Other information**: Hard to reproduce, but still a common problem. Try jumping against two blocks and as soon as you are high up go sideways around the block.

**Comment by re-ovo** [comment]
Fixed
