### ISSUE TITLE
[INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by samukatb** [re-ovo/Matrix-Issues#2407]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8, 1.12, 1.13, 1.14, 1.15, or 1.16 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.5 
**Incompatible plugin**: mcMMO
**Verbose messages (or) console errors**: No errors
**How/when does this happen**:  If the player has a high ping (100+) and the matrix blocks a hit, and mcmmo is active and applies the ability's damage, the player he attacked gets NaN absorption and becomes immortal.

**Comment by jiangdashao** [comment]
record a video

**Comment by samukatb** [comment]
> record a video

https://youtu.be/3Vxbp-79Es0 @jiangdashao 

In the video you can see in the top left corner that the first player has hearts, the other doesn't. This only happens when a player who is lagged hits another.

If I remove mcmmo, the bug doesn't happen, if I remove the matrix, the bug doesn't happen either.

**Comment by emanondev** [comment]
confirmed
