### ISSUE TITLE
[FP] Jesus

### ISSUE THREAD

**Issue by Pascalpex** [re-ovo/Matrix-Issues#2449]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.17.1
**Verbose messages**: https://pasteboard.co/Kjljpj5.png
**How/when does this happen**: Jumping from some height on slime blocks in water
**Video of false positive**: https://youtu.be/xM0q3zg7syc
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default

**Comment by Dmitri233** [comment]
It seems impossible to copy
`Matrix AntiCheat v6.8.19 | git-Paper-66 (MC: 1.19) | PAPER`
