### ISSUE TITLE
[BYPASS] Speed on Stairs

### ISSUE THREAD

**Issue by Pascalpex** [re-ovo/Matrix-Issues#2450]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.17.1
**Hacked client**: Sigma 5
**Link to hacked client**: https://sigmaclient.info/
**Cheat that bypassed**: Speed (Vanilla)
**Video of bypass**: https://youtu.be/TgUOaoYvf6Q
**Other information**: Only works when going up stairs

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by ImUtsarg** [comment]
this would basically work on any anticheat due to it being stairs and isnt really that much of an advantage

**Comment by xXSimoGamerXx** [comment]
It is not a problem up to a certain point, with hoppers, trapdoors, hoppers it is possible to use phase and vclip without problems. (Works on all client, no reports from Matrix)
