### ISSUE TITLE
[BYPASS] pearl highjump / fly

### ISSUE THREAD

**Issue by Minecon724** [re-ovo/Matrix-Issues#2462]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: test.matrix.rip
**Hacked client**: fdp (any client should work i guess)
**Link to hacked client**: https://github.com/UnlegitMC/FDPClient
**Cheat that bypassed**: vanilla fly 
**Video of bypass**:  https://streamable.com/2o80s3
**Other information**: 
you need to toggle fly at the right moment
speed over 5 didnt work (at least for me)
tested only with ender pearls

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by re-ovo** [comment]
it's pretty hard to reproduce in my testing

**Comment by Minecon724** [comment]
but its possible

**Comment by contionability** [comment]
easy to reproduce
Send y+3.5 and set Motion to 3.5 when teleported

**Comment by Minecon724** [comment]
> easy to reproduce Send y+3.5 and set Motion to 3.5 when teleported

you just need to turn on vanilla fly right after teleporting
i reported it a long time ago but still not fixed :/

**Comment by Minecon724** [comment]
fixed?

**Comment by re-ovo** [comment]
maybe, try hotfix6

**Comment by RedWay228** [comment]
https://staging.streamable.com/nlh5yq @re-ovo
