### ISSUE TITLE
[BYPASS] slight omnisprint bypass

### ISSUE THREAD

**Issue by Minecon724** [re-ovo/Matrix-Issues#2463]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config
^ official test server so idk

## Issue Information
**Server version**: test.matrix.rip
**Hacked client**: fdp
**Link to hacked client**: https://github.com/UnlegitMC/FDPClient
**Cheat that bypassed**: sprint
**Video of bypass**: https://streamable.com/trtm69
**Other information**: 
config shown on video

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by re-ovo** [comment]
I guess it will automatically help you rotate your head when sprinting
