### ISSUE TITLE
[BYPASS] Hitboxes

### ISSUE THREAD

**Issue by niemogewejsc** [re-ovo/Matrix-Issues#2464]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config
  official test server 

## Issue Information
**Server version**: test.matrix.rip
**Hacked client**: meteorclient
**Link to hacked client**: https://meteorclient.com
**Cheat that bypassed**: Hitboxes
**Video of bypass**: https://streamable.com/jy3zi8
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by re-ovo** [comment]
not a bypass, Matrix requires you to hit an entity twice to start calculating the hitbox, because it needs to track enough data
