### ISSUE TITLE
[FP] 

### ISSUE THREAD

**Issue by niemogewejsc** [re-ovo/Matrix-Issues#2465]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config
   official test server

## Issue Information
**Server version**: idk
**Verbose messages**: scaffold/tower
**How/when does this happen**: when i do godbridge
**Video of false positive**: https://streamable.com/uanr4p
**Other information**: 

## Configuration Files
**Link to checks.yml file**:

**Comment by Minecon724** [comment]
i dont think "godbridge" is a good word to describe it since it flagged just building up and placing one block on the edge
and this false positive is as old as the ac itself

**Comment by re-ovo** [comment]
1. type`/matrix verbose` before testing
2. report bugs in discord server before reporting it on GitHub issue tracker
