### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by Cyberyisus2g** [re-ovo/Matrix-Issues#2466]
## Troubleshooting Information

- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.17.1
**Hacked client**:  idk
**Cheat that bypassed**: Fly
**Video of bypass**: https://streamable.com/bnwn2x

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by Minecon724** [comment]
wow, thats a lot of info
