### ISSUE TITLE
Simplesit

### ISSUE THREAD

**Issue by Regomy** [re-ovo/Matrix-Issues#2468]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ProtocolLib v4.5.1 & Matrix Version: 6.5.0 Author: RE Premium: false ] Matrix and ProtocolLib are up-to-date
- [ Spigot 1.8.8 ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ Yes ] The issue happens on default config.yml and checks.yml
/sit ( When you stand up it flags, then kicks you ) - move detection

**Comment by AkariDream** [comment]
我在我的服务器内也有同样的问题
插件为GSit
当/sit后空格站起会被判定
*(坐在台阶和楼梯上无误报)
/crawl 趴着的时候站起会误报
因为原理是靠数据包发送屏障
但是这个屏障是不存在的
因此可能造成误报
