### ISSUE TITLE
Matrix Bypass

### ISSUE THREAD

**Issue by IAmKing00032** [re-ovo/Matrix-Issues#2471]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [x] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [x] The issue happens on default config.yml and checks.yml
- [x] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8 - 1.18.1
**Hacked client**: FDPClient
**Link to hacked client**: https://getfdp.today/
**Cheat that bypassed**: Killaura Velocity Speed Step Scaffold
**Video of bypass**: https://youtu.be/gDZx6jyM_6s
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by re-ovo** [comment]
😅

**Comment by re-ovo** [comment]
killaura is undetectable

**Comment by contionability** [comment]
草
