### ISSUE TITLE
[REQUEST] Geyser mark option

### ISSUE THREAD

**Issue by ThiemoBoven** [re-ovo/Matrix-Issues#2473]
**What features/checks do you need?:**
I would like to be able to mark a player as a Geyser player using the Matrix API. While using a custom build of Geyser the support for it no longer works and they will not be seen as geyser players.

By simply having the option to mark them as one through the API would solve this issue in the easiest way possible.
https://github.com/re-ovo/Matrix-Issues/wiki/GeyserMC-Support

**Comment by Encode42** [comment]
I believe the latest hotfix refers to this issue, therefore I will close it.

If not, feel free to re-open
