### ISSUE TITLE
[FP] Movement

### ISSUE THREAD

**Issue by AabegR** [re-ovo/Matrix-Issues#2475]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date - Using version 6.6.1 Hotfix1
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.16.2 tried 1.16.5 aswell -- Paper and Tuinity both same issue
**Verbose messages**: (21:10:11) AabegR failed Move check | unexpected vertical movement (motion: 0.083/-0.078, hor: 0.179, buffer: 0.484/false, ground: --, setback: +, vel: none, from: 3.166, past: 0.0, tags: noslow,air_bst,air_mdf) (+5) | vl:5 ping:3 tps:20.0 lp:7 component: move.vert ver: 1.18.x  -------(Thats only 1 I'm getting a bunch including unexpected vertical and horizontal movement)
**How/when does this happen**: Strafing to side or moving forward after bow shot. Also when eating gapples. More details in video
**Video of false positive**: https://youtu.be/rPcAfxbbJcM
**Other information**: I have Protocollib Updated and everything else, haven't had this issue. I have other servers but this is the only one with the issue. Could it be a plugin that's conflicting? I'm using the Duels plugin written by Realized... Also I have tried Matrix 6.5.0 same thing too.

## Configuration Files
**Link to checks.yml file**: Its default. The only part I changed was the cmds. But I also tried it with a freshly generated default yml.

Let me know whenever you're free, I can elaborate more if you need, thanks! :)

**Comment by AabegR** [comment]
I'm having the same issue in a completely different server 1.16.5 this time. This is using KitPVP. Didn't have this issue before :(

**Comment by re-ovo** [comment]
it's a 1.17+ client handling bug

**Comment by re-ovo** [comment]
Cannot be repaired in the short term

**Comment by AabegR** [comment]
> it's a 1.17+ client handling bug

Yep just found out lol, went on 1.16.5 and its clean. So its a bug in the client from 1.17+ that's affecting Matrix?

**Comment by re-ovo** [comment]
1.17+ client will send a position packet when right clicking

**Comment by AabegR** [comment]
Wait was this fixed?

**Comment by re-ovo** [comment]
yes, latest premium hotfix

**Comment by AabegR** [comment]
Oh you snake lol, is it coming trial-version?
