### ISSUE TITLE
[BYPASS] Matrix BHop

### ISSUE THREAD

**Issue by AdLmao** [re-ovo/Matrix-Issues#2477]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: FDPClient
**Link to hacked client**: https://github.com/UnlegitMC/FDPClient/
**Cheat that bypassed**: Speed
**Video of bypass**: 
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://paste.loliidc.cn/?8182ed2776c09219#3fw6nK8jRS7YmJaaJbixRTGhkBUTcweQiAYcW5Z8y2uz
**Link to config.yml file**:https://paste.loliidc.cn/?6cad71a42cba36c5#7cx3uPWPdZP3uwu9B2bFVPXqbHiUYHKziBwDSoywdPsu

**Comment by re-ovo** [comment]
Already patched in premium version, but it was not released for free users yet
