### ISSUE TITLE
[ERROR] Disky depedience

### ISSUE THREAD

**Issue by Norbiros** [re-ovo/Matrix-Issues#2479]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on 1.18.1 
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.18.1
**Error(s) found in console**:   [Matrix] Loaded class org.apache.commons.logging.impl.WeakHashtable from DiSky v3.7.0 which is not a depend, softdepend or loadbefore of this plugin.
**How/when does this happen**: On loading server.
**Other information**: Disky is plugin for managing discord bot using skript. I found this error... I don't know if you need to fix it. This is only warning...

## Configuration Files
I didn't change anything..

**Comment by re-ovo** [comment]
ignore it
