### ISSUE TITLE
[FP] Movement

### ISSUE THREAD

**Issue by tkirit** [re-ovo/Matrix-Issues#2480]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [x] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**1.12.2**: 
**tkirit failed Move check | unexpected vertical movement (motion: 0.0/-0.078, hor: 0.029, buffer: 0.157/true, ground: +-, setback: -, vel: none, from: 65, past: 0.0, tags: empty) (+5) | vl:10 ping:4 tps:20.0 lp:0 component: move.vert ver: 1.12.x**: 
**When walking on stairs in a shift, and also without it.**: 
**[Video of false positive](https://youtu.be/G411yuHGmuI)**: 
**Matrix Version 6.6.1 Hotfix 4, Server on LocalHost, Premium Version**: 

## Configuration Files
**Default configuration file**:

**Comment by Kylepoops** [comment]
Could you try it on 6.7.0, i cannot reproduce it on the latest version
