### ISSUE TITLE
[REQUEST FIX BUG ON LOGIN] 

### ISSUE THREAD

**Issue by diocan** [re-ovo/Matrix-Issues#2481]
hello I noticed that in my server you can do all the matrix commands even before the login can you fix?

**Comment by diocan** [comment]
my server is in paper 1.17.1 and i can kick player before login

**Comment by re-ovo** [comment]
Why care about this kind of thing? Executing the matrix command does not cause any serious impact

**Comment by diocan** [comment]
being that there are commands like matrix kick that allow players to be kicked out this for me is a serious problem since I have matrix in the server where the login is performed
