### ISSUE TITLE
[BYPASS] Matrix Speed

### ISSUE THREAD

**Issue by AdLmao** [re-ovo/Matrix-Issues#2483]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: Flux
**Link to hacked client**: flux.today
**Cheat that bypassed**: Speed(AAC4 Module) 
**Video of bypass**: 
**Other information**: nope

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by AdLmao** [comment]
I'll add the video later.

**Comment by re-ovo** [comment]
这东西连原版都跑不过

**Comment by AdLmao** [comment]
草

**Comment by re-ovo** [comment]
而且没有其他反作弊flag这玩意，你确定这是speed?

**Comment by AdLmao** [comment]
那就算了吧

**Comment by AdLmao** [comment]
确定啊

**Comment by AdLmao** [comment]
azzzzzzz

**Comment by AdLmao** [comment]
原版是5.8m/s,这个是7m/s
我不知道你那边是怎么测的
