### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by AdLmao** [re-ovo/Matrix-Issues#2484]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8
**Hacked client**: LiquidBounce+
**Link to hacked client**: https://github.com/WYSI-Foundation/LiquidBouncePlus
**Cheat that bypassed**: Fly
**Video of bypass**: https://www.bilibili.com/video/BV13S4y177Qc/
**Other information**: 

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by AdLmao** [comment]
嗯，我测了很久才测出来的
这回应该没什么大毛病

**Comment by re-ovo** [comment]
#2462 重复

**Comment by AdLmao** [comment]
呜呜呜

**Comment by contionability** [comment]
"Not Important"
指在Jatrex里面OP得一批
