### ISSUE TITLE
[WARN] [Matrix] [P] Bad Response

### ISSUE THREAD

**Issue by Bammyyy** [re-ovo/Matrix-Issues#2488]
[09:08:47 WARN]: [Matrix] [P] Bad Response
[09:09:17 INFO]: [Matrix] Restart verification of premium information...

Getting this warning when trying to login using the account information used to buy the premium version of the plugin.

Bought via this website: https://www.mc-market.org/resources/13999/
Username: Bammy

**Comment by re-ovo** [comment]
if u purchase plugin, you should dm me on discord to get your license info, it's not mcmarket account
