### ISSUE TITLE
[FP] Move

### ISSUE THREAD

**Issue by ABatareyka** [re-ovo/Matrix-Issues#2494]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Paper 1.12.2
**Verbose messages**: https://paste.twerion.net/todujecozu.yaml
**How/when does this happen**: If you stand on iron bars, you will soon be kicked
**Video of false positive**:  https://drive.google.com/file/d/119JTF8MtAWG2x5erZSIrYmYwae8xTnj6/view?usp=sharing
**Other information**: Metrix trial 6.6.2

## Configuration Files
**Link to checks.yml file**: default

**Comment by ABatareyka** [comment]
P.S. Sorry for bad quality of the video

**Comment by re-ovo** [comment]
I can't reproduce
