### ISSUE TITLE
Old versions False Positives

### ISSUE THREAD

**Issue by kokqi** [re-ovo/Matrix-Issues#2495]
My server is 1.18.1 version, but I have via backwards/via rewind plugins. So, my members join the server with 1.8.9, then he goes to mine new version blocks which are unbreakable for old version. And he got detected as cheating. 

and I received this messages: vanicksan tried to place/break a block too quickly (FastPlace/FastBreak)

**Comment by re-ovo** [comment]
Please don't use such plugin or disable fastbreak check. This just brings up a lot of compatibility issues
