### ISSUE TITLE
[BYPASS] Elytra Flight

### ISSUE THREAD

**Issue by WPWolker** [re-ovo/Matrix-Issues#2499]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**:  1.16.5
**Hacked client**:  DeadCode 1.12.2
**Link to hacked client**:  https://deadcodehack.org/ The client is private, there is no trial version 
**Cheat that bypassed**: Elytra Flight/Elytra+
**Video of bypass**: https://youtu.be/ILISWDFzgF4
**Other information**:  There is an assumption that the bypass of the check is the difference in versions
[matrix_log.txt](https://github.com/re-ovo/Matrix-Issues/files/8140438/matrix_log.txt)

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by re-ovo** [comment]
I don't think it's a bypass

I just need to improve setback system

**Comment by Overwrite987** [comment]
> > ## Troubleshooting Information
> > `Change - [ ] to - [X] to check the checkboxes below.`
> > 
> > * [x]   Matrix and ProtocolLib are up-to-date
> > * [x]   Matrix is running on a 1.8 or 1.12 to 1.17 server
> > * [x]   The issue happens on default config.yml and checks.yml
> > * [x]   I've tested if the issue happens on default config
> > 
> > ## Issue Information
> > **Server version**: 1.16.5 **Hacked client**: DeadCode 1.12.2 **Link to hacked client**: https://deadcodehack.org/ The client is private, there is no trial version **Cheat that bypassed**: Elytra Flight/Elytra+ **Video of bypass**: https://youtu.be/ILISWDFzgF4 **Other information**: There is an assumption that the bypass of the check is the difference in versions [matrix_log.txt](https://github.com/re-ovo/Matrix-Issues/files/8140438/matrix_log.txt)
> > ## Configuration Files
> > **Link to checks.yml file**: default **Link to config.yml file**: default
> 
> I am make this bypass for 1.18.2

Already fixed ib newest version lul
