### ISSUE TITLE
[FP] false movement detection

### ISSUE THREAD

**Issue by Overwrite987** [re-ovo/Matrix-Issues#2500]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ X] Matrix and ProtocolLib are up-to-date (Protocollib-4.5.1)
- [ ] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [ ] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
1.12.2 - Dionysus:
everything is present in the video
I started noticing this after installing version 6.7.0 alpha:
https://drive.google.com/file/d/1ZO1SuQOF0A2JNYc3B-KcxXIlBhImcwFJ/view?usp=sharing:
these false positives occur not only in the case of a cactus, but also during normal damage. for example, if a player participates in PVP

## Configuration Files
https://pastebin.com/KwgttL1P:

**Comment by Kylepoops** [comment]
it's fixed and should be closed now @Overwrite987 @re-ovo
