### ISSUE TITLE
[BYPASS] NoFall

### ISSUE THREAD

**Issue by RedWay228** [re-ovo/Matrix-Issues#2502]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9 (eu.loyisa.cn)
**Hacked client**: FDPClient
**Link to hacked client**: https://getfdp.today/
**Cheat that bypassed**: NoFall
**Video of bypass**: 
**Other information**: https://github.com/UnlegitMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/NoFall.kt#L349

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by contionability** [comment]
already fixed isn't it?
no longer work in PikaNetwork
@re-ovo :(
