### ISSUE TITLE
[BYPASS] Powdered snow walk

### ISSUE THREAD

**Issue by jermaCraft** [re-ovo/Matrix-Issues#2503]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.18.1
**Hacked client**: Hydra
**Link to hacked client** : https://hydra-utility-mod.yolasite.com/
**Cheat that bypassed**: jesus (Powdered snow)
**Video of bypass**: https://streamable.com/yexsfg

## Configuration Files
**Link to checks.yml file**: Default
**Link to config.yml file**: Default

**Comment by re-ovo** [comment]
Sorry, matrix won't patch it shortly
