### ISSUE TITLE
[BYPASS] Matrix 6.6.3 Fly Bypass

### ISSUE THREAD

**Issue by ffffffffawd** [re-ovo/Matrix-Issues#2504]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [x] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: AirplanePurur-1.17.1
**Hacked client**: FDPClient
**Link to hacked client**: [GetFDP.Today](http://GetFDP.Today)
**Cheat that bypassed**: Fly
**Video of bypass**: 
**Other information**: [Kt code](https://github.com/UnlegitMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/flys/other/Matrix117Fly.kt)

## Configuration Files
**Link to checks.yml file**:[PasteBin checks.yml](https://pastebin.com/RXpspdAc)
**Link to config.yml file**:[PasteBin config.yml](https://pastebin.com/rnvXsEQQ)

**Comment by re-ovo** [comment]
1. don't use outdated matrix, it has been patched long time ago
2. if u think it's really a bypass, provide video proof

**Comment by ffffffffawd** [comment]
oh sorry
