### ISSUE TITLE
[BYPASS] Speed

### ISSUE THREAD

**Issue by RedWay228** [re-ovo/Matrix-Issues#2510]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.17 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: FDPClient
**Link to hacked client**: https://getfdp.today/
**Cheat that bypassed**: Speed
**Video of bypass**: 
**Other information**: https://github.com/UnlegitMC/FDPClient/blob/85a61262a18648164b7475063ce71aba205dd722/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/speeds/other/MatrixHop3.kt

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by Kylepoops** [comment]
Can you record a video for this, thanks
