### ISSUE TITLE
[FP] ka.prot.5

### ISSUE THREAD

**Issue by honigbrai** [re-ovo/Matrix-Issues#2511]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Verbose messages**:  [Flag] (Matrix) Vampurp failed KILLAURA(vl:5): combat not following the vanilla protocol: #05 (val: 102.422) component: ka.prot.5 | KILLAURA: 5 vl(s)
**How/when does this happen**: spin over 90° in 1 server tick
**Video of false positive**: https://cdn.discordapp.com/attachments/832345181411606618/956932616341299250/Desktop_2022.03.25_-_16.07.29.03.DVR.mp4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://github.com/re-ovo/Matrix-Issues/blob/master/checks.yml

**Comment by re-ovo** [comment]
that's how it works, if you don't like it, disable it
