### ISSUE TITLE
Own packet-based inventories system [INCOMPATIBILITY] 

### ISSUE THREAD

**Issue by MaxWainer** [re-ovo/Matrix-Issues#2515]
## Troubleshooting Information
- [X] The incompatible plugin is up-to-date
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
```
>ver
[16:49:29 INFO]: This server is running CraftBukkit version git-Spigot-79a30d7-f4830a1 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[16:49:29 INFO]: This is a final build for 1.12.2. Please see https://www.spigotmc.org/ for details about upgrading.
```
**Incompatible plugin**: 
`DevGui`
**Verbose messages (or) console errors**: 
`No any`
**How/when does this happen**: 
`When opens gui`
**Video of incompatibility**: 
https://youtu.be/SmnJ6-ok0fs
**Other information**: 
If delete matrix, bug will gone

I am not using PLib for this, just sending packets via NetworkManager

## Configuration Files
**Link to checks.yml file**:
`They fully default`

**Comment by re-ovo** [comment]
I don't think it was caused by matrix

**Comment by re-ovo** [comment]
Also please make sure you are using 6.7.0 hotfix02+
