### ISSUE TITLE
[BYPASS] - Killaura

### ISSUE THREAD

**Issue by Overwrite987** [re-ovo/Matrix-Issues#2518]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**1.12.2**: 
**akrien-premium**: 
**https://vk.com/akrienclient**:
**KIllAura**: 
**[Video of bypass](https://drive.google.com/file/d/1q6Gk4kIVO54KXk0q7RujKHpSn2In9YEo/view?usp=sharing)**: 
**u know...**: 

## Configuration Files
**[Link to checks.yml file](https://hastebin.app/627fd1d1b94bd5001c8fbbcd)**: 
**https://hastebin.app/627fd1f6b94bd5001c8fbbce**:

**Comment by contionability** [comment]
Killaura is very easy to bypass
no need to report this lol
