### ISSUE TITLE
[REQUEST] Add new check and new checks.yml

### ISSUE THREAD

**Issue by PaperTrain05** [re-ovo/Matrix-Issues#2519]
**What features/checks do you need?:**
Checks:
ProxyCheck

Features:
New Checks.yml: **inspired by checks of Matrix 5.1.1+**
https://mega.nz/file/d40gQJrB#DapEkei8iO7KEAOfNA62JvKisyr3siOMKzGj8Gf2x3w

Benefit: 
Advantage in managing (almost) all checks with dedicated strings. For the new check the AntiProxy would be a good thing and can only be used by premium customers above :)

**Comment by re-ovo** [comment]
Matrix is a anticheat, not a antibot
