### ISSUE TITLE
[BYPASS] 

### ISSUE THREAD

**Issue by Overwrite987** [re-ovo/Matrix-Issues#2521]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.12.2
**Hacked client**: mathax
**Link to hacked client**: https://mathaxclient.xyz/Download
**Cheat that bypassed**: noslow
**Video of bypass**: https://disk.yandex.ru/d/0moflfi05AbDzQ
**Other information**: uknow...

## Configuration Files
**Link to checks.yml file**: https://hastebin.app/6289f512eb779c001c92c022
**Link to config.yml file**: *default*

**Comment by re-ovo** [comment]
![image](https://user-images.githubusercontent.com/21152113/169763368-c28703b3-22b5-4f7d-81a3-a33f18f39eb5.png)
