### ISSUE TITLE
[FP] Move in combo mode  

### ISSUE THREAD

**Issue by SlimeBluKing** [re-ovo/Matrix-Issues#2522]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: Wine 1.8.8 
**Verbose messages**:  Vertical Movement
**How/when does this happen**: In combo mode, knockback master up-to-date
**Video of false positive**: https://www.youtube.com/watch?v=ymZ42wxSC8U
**Other information**: 

## Configuration Files
**Link to checks.yml file**: https://www.toptal.com/developers/hastebin/cubaqokife.yaml

**Comment by re-ovo** [comment]
Are you using any knockback modifier plugin or spigot fork?

**Comment by SlimeBluKing** [comment]
Wine spigot and knockback master
