### ISSUE TITLE
[ERROR] 

### ISSUE THREAD

**Issue by AlexSuper144** [re-ovo/Matrix-Issues#2524]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.18
**Error(s) found in console**: Server thread/ERROR Could not load 'plugins/Matrix_6.8.11.jar' in folder 'plugins
**How/when does this happen**:  When i put the plugin into the plugins folder and restarted the server the first time
**Other information**: 

## Configuration Files
**Link to checks.yml file**: No
**Link to config.yml file**: No

**Comment by re-ovo** [comment]
if you purchased plugin, just ask it in discord support channel
