### ISSUE TITLE
[BYPASS] Fly

### ISSUE THREAD

**Issue by kotonemywaifu** [re-ovo/Matrix-Issues#2525]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [X] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: spigot-v1_8_R3
**Hacked client**: Fluidity
**Link to hacked client**: https://github.com/kotonemywaifu/Fluidity
**Cheat that bypassed**: [Fly.kt](https://github.com/kotonemywaifu/Fluidity/blob/main/src/main/java/me/liuli/fluidity/module/modules/movement/Fly.kt)
**Video of bypass**: https://www.youtube.com/watch?v=uxZfZPuG884
**Other information**: working on Matrix 6.7.0 (the latest one of cracked version that i can found haha) and Jartex/Pika Network

## Configuration Files
**Link to checks.yml file**: default
**Link to config.yml file**: default

**Comment by rikoshet185** [comment]
лиули пидор

**Comment by Nelass1c** [comment]
Какой же он хуесос

**Comment by re-ovo** [comment]
编译不了，绝 ☹️ com.github.asbyth:ForgeGradle:ddb1eb0好像寄了

**Comment by kotonemywaifu** [comment]
> 编译不了，绝 frowning_face com.github.asbyth:ForgeGradle:ddb1eb0好像寄了

'-'

**Comment by kotonemywaifu** [comment]
> 编译不了，绝 frowning_face com.github.asbyth:ForgeGradle:ddb1eb0好像寄了

尝试使用这个https://github.com/kotonemywaifu/ForgeGradle/commits/FG_2.1
我曾经有fork过asbyth的forgegradle

**Comment by Darkingg12** [comment]
> 

man link dont work plz give new
