### ISSUE TITLE
[BYPASS] fly

### ISSUE THREAD

**Issue by Zerolysimin** [re-ovo/Matrix-Issues#2526]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [V] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [V ] The issue happens on default config.yml and checks.yml
- [V] I've tested if the issue happens on default config

## Issue Information
**Server version**: 
**Hacked client**: FDP
**Link to hacked client**: https://github.com/SkidderMC/FDPClient src.  https://fdpinfo.github.io/ web.
**Cheat that bypassed**: https://github.com/SkidderMC/FDPClient/tree/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/flys
**Video of bypass**: https://youtu.be/MAx5KjcXg2g
**Other information**: they got tons of matrix bypasses too ( crictical, inf fly flag ). try patch it

## Configuration Files
**Link to checks.yml file**: defa
**Link to config.yml file**: defa

**Comment by Zerolysimin** [comment]
https://github.com/WYSI-Foundation/LiquidBouncePlus/blob/no-wdl/src/main/java/net/ccbluex/liquidbounce/features/module/modules/movement/LongJump.java. matrixflag longjump bypass too. i tested

**Comment by re-ovo** [comment]
use ticket system to report bugs please
