### ISSUE TITLE
[FP] 正常破坏海带时报block

### ISSUE THREAD

**Issue by DreamVoid** [re-ovo/Matrix-Issues#2530]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [X] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.19 Purpur
**Verbose messages**: `玩家名 failed Block check | break block with incorrect delay (type A) (+0) | vl:0 ping:37 tps:20.0 lp:7 component: blk.delay ver: 1.19.x` （全都是这个）
**How/when does this happen**: 玩家潜水找到海带，左键破坏，但是要破坏好几下才会掉落
**Video of false positive**: https://user-images.githubusercontent.com/45266046/181235379-270494fa-8424-4e47-8d74-d5f33c976f05.mp4
**Other information**: 

## Configuration Files
**Link to checks.yml file**: 默认，只改了自定义命令部分

**Comment by re-ovo** [comment]
无法复现
