### ISSUE TITLE
[FP] Move in combo Mode

### ISSUE THREAD

**Issue by PaperTrain05** [re-ovo/Matrix-Issues#2532]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 (WineSpigot)
**Verbose messages**: Video
**How/when does this happen**: Video
**Video of false positive**: https://youtu.be/Zzq6pVcaYUM
**Other information**: ComboMode (plugins I use)
https://www.spigotmc.org/resources/knockbackmaster-%E2%AD%90-professional-custom-knockback-and-hits-for-pvp.42721/
## Configuration Files
**Link to checks.yml file**: Default Checks.yml

**Comment by re-ovo** [comment]
report on discord server first pls

**Comment by PaperTrain05** [comment]
I'm 'sub customer', i don't have acces on discord server :(
