### ISSUE TITLE
[BYPASS] NoFalls 

### ISSUE THREAD

**Issue by RedWay228** [re-ovo/Matrix-Issues#2537]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.9
**Hacked client**: FDPClient 
**Link to hacked client**: https://fdpinfo.github.io/download
**Cheat that bypassed**: NoFall
**Video of bypass**: 
**Other information**: https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/nofalls/matrix/MatrixNewNofall.kt - MatrixNew
https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/player/nofalls/matrix/MatrixCollideNofall.kt - MatrixCollide

## Configuration Files
**Link to checks.yml file**: 
**Link to config.yml file**:

**Comment by re-ovo** [comment]
make sure u are using latest version
