### ISSUE TITLE
[BYPASS] Tower

### ISSUE THREAD

**Issue by Stablelly** [re-ovo/Matrix-Issues#2544]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [ ] Matrix and ProtocolLib are up-to-date
- [ ] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ ] The issue happens on default config.yml and checks.yml
- [ ] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8
**Hacked client**: FDPClient
**Link to hacked client**: https://github.com/SkidderMC/FDPClient/blob/main/src/main/java/net/ccbluex/liquidbounce/features/module/modules/world/Scaffold.kt
**Cheat that bypassed**: Tower, mode motionTP2
**Video of bypass**: None
**Other information**: 如果拉高timer，还可以更快，1秒内甚至可以搭上10格以上

**Comment by Spinyfish** [comment]
lololololol

**Comment by Stablelly** [comment]
timer1的时候和ncptower一样快
