### ISSUE TITLE
[FP] ⚠️HUGE PROBLEM 1.8⚠️

### ISSUE THREAD

**Issue by FairGames** [re-ovo/Matrix-Issues#2552]
## Troubleshooting Information
`Change - [ ] to - [X] to check the checkboxes below.`
- [X ] Matrix and ProtocolLib are up-to-date
- [ 1.8] Matrix is running on a 1.8 or 1.12 to 1.18.2 server
- [ X] The issue happens on default config.yml and checks.yml
- [ X] I've tested if the issue happens on default config

## Issue Information
**Server version**: 1.8.8 
**Verbose messages**: 
Everything is on the video
**How/when does this happen**: 
Every first hit while sprinting
**Video of false positive**: 
https://gyazo.com/eed6c5b4f29de645b832a68d9be0f00e
**Other information**: 
Happening only with speed 1 potion while SPRINTING
Caused by attacker slowdown in spigot i think

## Configuration Files
**Link to checks.yml file**:
[checks.txt](https://github.com/re-ovo/Matrix-Issues/files/10366870/checks.txt)

**Comment by FairGames** [comment]
still false positive

**Comment by re-ovo** [comment]
![image](https://user-images.githubusercontent.com/21152113/213418835-cd795ca9-1124-4d7f-bc7c-5858a5f2e342.png)

**Comment by re-ovo** [comment]
If you are a paying user, please use discord's ticket function, otherwise I will not provide any support

**Comment by FairGames** [comment]
i am reporting default's config false positive
Caused by attacker slowdown of PvP spigots.
Effect: Speed 1 + only
